unit TestSMBExcelClassMembers;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Excel_TLB, SMBExcel, System.Generics.Collections;
const
  FileNamePattern1 = 'C:\Users\1\Google Диск\RAD Studio Projects\SMBComponents\SMBReport\Patterns\pattern1.xlsx';
type
  // Test methods for class TSMBExcel

  TestTSMBExcelClassMembers = class(TTestCase)
  strict private
    FExcel: ExcelApplication;
    FSMBExcel: TSMBExcel;
    WB: ExcelWorkbook;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure ClassOpenWorkbook;
    procedure ClassCreateExcelObj;
    procedure ClassFreeExcelObj;
    procedure ClassCheckExcelInstall;
    procedure ClassShow;
    procedure ClassHide;
    procedure ClassReadCellA1;
  end;

implementation
procedure TestTSMBExcelClassMembers.ClassCheckExcelInstall;
begin
  CheckTrue(TSMBExcel.CheckExcelInstall);
end;

procedure TestTSMBExcelClassMembers.ClassCreateExcelObj;
begin
  CheckTrue(Assigned(FExcel));
end;

procedure TestTSMBExcelClassMembers.ClassFreeExcelObj;
begin
  CheckTrue(TSMBExcel.FreeExcelObject(FExcel));
  CheckFalse(Assigned(FExcel));
  FExcel    := TSMBExcel.CreateExcelObject();
end;

procedure TestTSMBExcelClassMembers.ClassHide;
begin
  WB        := TSMBExcel.OpenWorkbook(FExcel, FileNamePattern1);
  TSMBExcel.Show(FExcel);
//  ShowMessage('Before Hide');
  TSMBExcel.Hide(FExcel);
//  ShowMessage('After Hide');

end;

procedure TestTSMBExcelClassMembers.ClassShow;
begin
  WB        := TSMBExcel.OpenWorkbook(FExcel, FileNamePattern1);
  TSMBExcel.Show(FExcel);
//  ShowMessage('Test');
end;

procedure TestTSMBExcelClassMembers.SetUp;
begin
  inherited;
  FExcel    := TSMBExcel.CreateExcelObject();
end;

procedure TestTSMBExcelClassMembers.TearDown;
begin
  inherited;
  TSMBExcel.FreeExcelObject(FExcel);
end;

procedure TestTSMBExcelClassMembers.ClassOpenWorkbook;
begin
  CheckNotNull(TSMBExcel.OpenWorkbook(FExcel, FileNamePattern1));
end;

procedure TestTSMBExcelClassMembers.ClassReadCellA1;
begin
  WB        := TSMBExcel.OpenWorkbook(FExcel, FileNamePattern1);
  CheckEquals('Text in cell A1', FExcel.Cells.Item[1, 1]);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSMBExcelClassMembers.Suite);
end.
