unit TestSMBReport;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SMBReport, SMBExcel;
const
  FileNamePattern1    = 'C:\Users\1\Google Диск\RAD Studio Projects\SMBComponents\SMBReport\Patterns\pattern1.xlsx';
type
  // Test methods for class TSMBReport

  TestTSMBReport = class(TTestCase)
  strict private
    FSMBReport: TSMBReport;
    Pattern: TSMBExcel;
    Destination: TSMBExcel;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure StartFromC5;
  end;

implementation

procedure TestTSMBReport.SetUp;
begin
  Pattern := TSMBExcel.Create(FileNamePattern1);
  Destination := TSMBExcel.Create();
  FSMBReport := TSMBReport.Create(Pattern, Destination);
end;

procedure TestTSMBReport.StartFromC5;
begin
  FSMBReport.StartFrom('C5');
  CheckEquals('C5', FSMBReport.CurrentCellAddress);
end;

procedure TestTSMBReport.TearDown;
begin
  FSMBReport.Free;
  FSMBReport := nil;
  Pattern.Free;
  Pattern := nil;
  Destination.Free;
  Destination := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSMBReport.Suite);
end.

