unit TestSMBExcel;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SMBExcel, System.Variants, Excel_TLB, System.Generics.Collections;

const
  FileNamePattern1 = 'C:\Users\1\Google Äèñê\RAD Studio Projects\SMBComponents\SMBReport\Patterns\pattern1.xlsx';
type
  // Test methods for class TSMBReport

  TestTSMBExcel = class(TTestCase)
  private
    E: TSMBExcel;
    Range: ExcelRange;
    WBList: TList<ExcelWorksheet>;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure CreateExcelAndOpenWorkbookPattern1;
    procedure GetWorksheetList1;
    procedure GetListOfWorksheet;
    procedure GetCountOfWorksheet;
    procedure GetActiveWorksheet;
    procedure SetActiveWorksheet;
    procedure FindCellTextParam1;
    procedure FindRangeByName;
    procedure CopyRangeA10B11ToG17;
  end;

implementation
uses
  Vcl.Dialogs;

procedure TestTSMBExcel.CopyRangeA10B11ToG17;
begin
  Range := E.Range['Ëèñò1', 'RangeA10B11'];
  E.Copy(Range, E.Worksheet['Ëèñò1'].Range['G17', EmptyParam]);
  E.Show;
  ShowMessage('Test');
end;

procedure TestTSMBExcel.CreateExcelAndOpenWorkbookPattern1;
begin
  CheckNotNull(E);
end;

procedure TestTSMBExcel.FindCellTextParam1;
begin
  Range := E.Field['Ëèñò1', '#Param1'];
  CheckEquals('#Param1', Range.Value2);
end;

procedure TestTSMBExcel.FindRangeByName;
begin
  Range := E.Range['Ëèñò1', 'RangeE7'];
  CheckEquals('123', Range.Value2);
end;

procedure TestTSMBExcel.GetListOfWorksheet;
begin
  WBList := E.Worksheets;
  CheckNotNull(WBList);
end;

procedure TestTSMBExcel.GetCountOfWorksheet;
begin
  WBList := E.Worksheets;
  CheckEquals(3, WBList.Count);
end;

procedure TestTSMBExcel.GetActiveWorksheet;
begin
  CheckEquals('Ëèñò1', E.ActiveWorksheet.Name);
end;

procedure TestTSMBExcel.SetActiveWorksheet;
begin
  E.ActiveWorksheet := E.Worksheet['Ëèñò2'];
  CheckEquals('Ëèñò2', E.ActiveWorksheet.Name);
end;

procedure TestTSMBExcel.SetUp;
begin
  inherited;
  E := TSMBExcel.Create(FileNamePattern1);
end;

procedure TestTSMBExcel.TearDown;
begin
  inherited;
  E.Free;
end;

procedure TestTSMBExcel.GetWorksheetList1;
begin
  CheckNotNull(E.Worksheet['Ëèñò1']);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSMBExcel.Suite);
end.

